# Site settings
baseURL = "https://fernandomachado90.github.io/"
languageCode = "en-us"
title = "Fernando Machado"
theme = "hugo-split-theme"
canonifyurls = true
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]
googleAnalytics = ""
copyright = "&copy; 2020 Fernando Machado"

[params]
  author = "Fernando Machado"
  description = "Fernando Machado. Software developer, agile enthusiast and passionate teacher."
  shareImage = "images/social.jpg"
  twitterHandle = "fernandomach7do"

  # Favicon
  favicon = "favicon.ico"

  [params.custom.css]
    enable = true

  # Section - Visual
  [params.visual]
    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  [[params.links]]
    [params.links.list1]
      heading = "Work"

      [[params.links.list1.link]]
        text = "GitHub"
        url = "https://github.com/fernandomachado90"

      [[params.links.list1.link]]
        text = "Medium"
        url = "https://medium.com/@fernandomachado90"

      [[params.links.list1.link]]
        text = "LinkedIn"
        url = "http://linkedin.com/in/fernandomachado90"

  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/fernandomach7do"

      [[params.links.list2.link]]
        text = "Facebook"
        url = "https://facebook.com/fernandomachado90"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "https://instagram.com/fernandomach7do"

  [[params.links]]
    [params.links.list3]
      heading = "Contact"

      [[params.links.list3.link]]
        text = "Email"
        url = "mailto:lfmachado90@gmail.com"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
