baseURL = "https://fernandomachado90.github.io/"
languageCode = "en-us"
title = "Fernando Machado"
theme = "aerial"
Copyright = "© Fernando Machado 2020"
canonifyurls = true

[params]
  name = "fernando machado"
  about = "software developer &nbsp;&bull;&nbsp; agile enthusiast &nbsp;&bull;&nbsp; passionate teacher"
  copyright = "Fernando Machado"
  bg_scroll = "stop"
  favicon = "favicon.ico"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin-square"
  link = "http://linkedin.com/in/fernandomachado90"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/fernandomachado90"

[[params.social]]
  medium = "Medium"
  icon = "align-left"
  link = "https://medium.com/@fernandomachado90"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/fernandomach7do"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "https://facebook.com/fernandomachado90"

[[params.social]]
  medium = "Instagram"
  icon = "instagram"
  link = "https://instagram.com/fernandomach7do"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:lfmachado90@gmail.com"
